#! /bin/bash
ifss=$IFS
IFS='[';
j=0;
for i in `cat $1`; do
	linha[$j]=`echo $i | tr -d \"}{]: | sed "s:,:,\ :g" | tr -d " " | tr , " "`
	let j++
done

estados=${linha[2]};
transicoes=${linha[3]};
finais=${linha[${#linha[@]}-1]};
iniciais=${linha[${#linha[@]}-2]};

for (( i = 4; i < ${#linha[@]} -2; i++ ));do
	grafo="$grafo${linha[$i]}"
done

IFS=$ifss
grafo=(${grafo})
grafo[${#grafo[@]}-1]="${grafo[${#grafo[@]}-1]}" | head -n 1
estados=($estados)
transicoes=($transicoes)
iniciais=($iniciais)
finais=($finais)

for i in ${!finais[@]}; do
	for j in ${!estados[@]}; do
		if [[ ${finais[$i]} == ${estados[$j]} ]]; then
			let b=141+$j
			finais[$i]=$(echo -e "\0$b")
			break;
		fi
	done

done

for i in ${!iniciais[@]}; do
	for j in ${!estados[@]}; do
		if [[ ${iniciais[$i]} == ${estados[$j]} ]]; then
			let b=141+$j
			iniciais[$i]=$(echo -e "\0$b")
			break;
		fi
	done

done

for (( i = 0; i < ${#grafo[@]} ; i+=3 )); do
	for j in ${!estados[@]}; do
		if [[ ${grafo[$i]} == ${estados[$j]} ]]; then
			let b=141+$j
			grafo[$i]=$(echo -e "\0$b")
			break;
		fi
	done

done
for (( i = 2; i < ${#grafo[@]} ; i+=3 )); do
	for j in ${!estados[@]}; do
		if [[ ${grafo[$i]} == ${estados[$j]} ]]; then
			let b=141+$j
			grafo[$i]=$(echo -e "\0$b")
			break;
		fi
	done

done


for i in ${!estados[@]}; do
	let b=141+$i
	estados[$i]=$(echo -e "\0$b")
done

for ((i = 0; i < ${#estado[@]}; i++ )); do
	estados[$i]=$(echo ${estado[$i]} | sed "s:\ :,:g")
done

inicial=$(echo ${iniciais[@]} | sed "s:\ :,:g")

caminho(){
	atual=$1
	for j in ${teste[@]}; do
		local next=''
		for i in $(echo $atual | sed "s:,::g" | grep -o .); do
			for (( k = 0; k < ${#grafo[@]}; k=k+3 )); do
				if [[ ${grafo[$k+1]} == "#" || ${grafo[$k]} == "$i" && ${grafo[$k+1]} == "$j" ]];then
					next="$next${grafo[$k+2]}"
				fi
			done
		done
		[[ -z $next ]] && break
		next=$(echo $next | grep -o . | sort -n | tr -d '\n')
		atual=$(echo $next | tr -s '\0-\255')
	done
}
while true; do
	read teste
	c=1
	[[ -z $teste ]] && exit 0;
	teste=($(echo $teste | grep -o .))
	for i in ${teste[@]}; do
		b=0
		for j in ${transicoes[@]}; do
			[[ $i == $j || $i == "#" ]] && { b=1; break; }
		done
		[[ $b -eq 0 ]] && { c=0; break; }
	done
	[[ $c -eq 1 ]] && caminho $inicial
	result="Nao"
	[[ $c -eq 1 ]] && {
	for i in $(echo ${atual[@]} | grep -o .); do
		for j in ${finais[@]}; do
			if [[ "$i" == "$j" ]]; then
				result="Sim";
			fi
		done
		[[ "$result" == "Sim" ]] && break;
	done;}
	echo $result
done
