#! /bin/bash
declare -a list=(1001 1002 1003 1004)

show() {
    local -a results=()
    let idx=$2
    for (( j = 0; j < $1; j++ )); do
        if (( idx % 2 )); then results=("${results[@]}" "${list[$j]}"); fi
        let idx\>\>=1
    done
    echo "${results[@]}"
}

let n=${#list[@]}
for (( i = 1; i < 2**n; i++ )); do
    show $n $i
done

#!/bin/bash
ifss=$IFS
IFS='[';
j=0;
for i in `cat $1`; do

	linha[$j]=`echo $i | tr -d \"}{]: | sed "s:,:,\ :g" | tr -d " " | tr , " "`
	let j++
done

estados=${linha[2]};
transicoes=${linha[3]};
finais=${linha[${#linha[@]}-1]};
iniciais=${linha[${#linha[@]}-2]};

echo "estados    ::  $estados"
echo "transicoes ::  $transicoes"
echo "iniciais   ::  $iniciais"
echo "finais     ::  $finais"
IFS=$ifss

estados=($estados)
transicoes=($transicoes)
iniciais=($iniciais)
finais=($finais)
tam=${#estados[@]}
let tam2=2**tam

gerar(){
	let n=$1+1
	[[ -z ${estados[$1]} ]] || { l=${estados[$1]} ; echo $l; }

	if [[ $1 -lt $tam ]]; then
		gerar $n
	fi

}

gerar 0
